### ISSUE TITLE
Does it polls continously?

### ISSUE THREAD

**Issue by i0natan** [bbc/sqs-consumer#108]
Does the consumer continue to poll while processing incoming messages? I'm concerned whether it doesn't work sequentially and pausing the polling while handling messages as this can starve the server (if for example many messages wait on the queue and the server has capacity to handle many more messages than exist in the batch)

**Comment by niklasR** [comment]
No, it does not. See [code](https://github.com/bbc/sqs-consumer/blob/035bc7dd084ff4fc824e69d75aa11495bc19e5fd/index.js#L106).

If you want to do that, I'd recommend creating multiple instances of sqs-consumer.
I can't tell you whether this is actually an issue for you, as I don't know your specific application.

Hope that helps.

**Comment by i0natan** [comment]
@niklasR you should consider this as an issue - a consumer should fetch as many messages that its hardware allows and scaling should be done on the infrastructure level and not via code. When you create an anemic consumer, you force the code to base the scale on software

**Comment by niklasR** [comment]
No, that would not allow us to distribute load easily across multiple machines.

A consumer fetches messages when it is ready to process more messages.

If you want to run multiple threads in parallel, you're welcome to do that, just spawn your own processes. 

See also SQS best practice examples: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-throughput-horizontal-scaling-and-batching.html

**Comment by i0natan** [comment]
Can you explain that message:
"No, that would not allow us to distribute load easily across multiple machines" - why?

This article repeats what we both suggest - scale out when you need. However, you believe that a single consumer utilizes 100% of node resources when it process messages - that is not true. While a node processes a batch of 20 messages, its cpu/memory can be on 20% and its ready for more. This approach leaves the developer with a very challenging and not standard way of scaling - he should replicates the consumber upfront or try to measure performance on run time

I suggest using the standards way of scaling - overload a process as much requests/messages as possible, let the infrastructure (AWS/K8S/etc) makes the scaling based on the resource utilization. When it will scale to two machines, you'll have two consumers fetching messages all the time

**Comment by niklasR** [comment]
I hear you. But you say
> you force the code to base the scale on software

Whether it's implemented in this library, or outside of it, does not make a difference, does it?

The SQS limit of messages fetched is 10.
Any 'fetching how much hardware allows' has to wrap around this, and be outside of the scope for just consuming the queue.
We are only trying to provide a simple interface for SQS, working with the AWS limits, and not a scaling mechanism - that is the objective here.

**Comment by i0natan** [comment]
"We are only trying to provide a simple interface for SQS, working with the AWS limits, and not a scaling mechanism - that is the objective here"

Exactly.

But you're making a very limiting scaling decision: you stop fetching messages while processing because you believe that "fetches messages when it is ready to process more messages". 

The contract between package authors and developer is: the packages operates at *maximum througut, the developer is responsible to balance its usage and the scaling. What you've done is like a logger or SQL driver author limiting their package throughput. Did you ever see something like that?

**Comment by niklasR** [comment]
I have two questions
1) What is that contract you're speaking of?
2) How would we know that node is busy processing messages and not just utilising all resources consuming messages if we were to poll without a limit?
We need to keep resources to process messages - polling forever would use up resources. Especially since the limit we're bound by if we're not at high CPU or Memory utilisation is IO - fetching more messages is not going to increase processing in that case. 

There are other libraries available that allow you to specify a concurrency, how many consumers are running in parallel. It is trivial to copy that behaviour by wrapping this library, too.

**Comment by i0natan** [comment]
1&2. Contract = a standard. Consider Express - does it concern about how much messages can be processed? Does it process X messages at a time before listening on the socket again? No. it overloads the handlers with as many messages as possible leaving the throughput/capacity challenge to the developer. This way, each node/process is utilized 100% before a scaling tool decides to add more nodes.

**Comment by niklasR** [comment]
Express is a framework which works very differently - scaling can be done on the infrastructure more easily with a routing layer distributing the requests across instances. You cannot do that with SQS.

**Comment by i0natan** [comment]
Web server has another layer of complexity but the same principles apply - it accepts as many requests as possible and relying on infrastructure to handle the *node/machine* scale. It works on 100% throughput. Same said for all loggers, email sender/receiver, etc

**Comment by ravenscar** [comment]
I am not a developer on this project but we use it extensively nearly anywhere we use SQS as it has a nicer interface and cleaner setup than using SQS directly.

@i0natan If you really just want to deliver all messages to a single machine in the same manner as an an express server handles web requests, then use SNS instead of SQS. You can evan literally use express to handle the messages. Depending on your use case this may be perfect to you.

WRT to SQS I do not think than an analogy to web servers such as express is relevant as the topology of the request model is fundamentally different. It would be unusual for any non-trivial application to be directly deployed on express and available to the internet, it is standard for them to be placed behind a reverse proxy or load balancer (e.g. AWS ELB/ALB, ngnix, HAProxy etc). This is what allows scaling not express, express has no magic in it stopping it's use at 100% of your resources, it will happily attempt to use 5000% of your resources until everything fails.

Even if this feature was to be considered I do not think it would be possible to do it with SQS due to the visibility timeouts, which would cause messages to be delivered/processed over and over in an unrecoverable pattern as soon as the consumer ran out of resources.

This overuse of resources is exactly what many of us are using queues to avoid, and pre-fetching all the messages off a queue is the antithesis of a good queuing system and often hinders scaling.
