### ISSUE TITLE
handleMessage not reliably invoked

### ISSUE THREAD

**Issue by kodayashi** [bbc/sqs-consumer#125]
The function I'm passing to handleMessage doesn't seem to be reliably invoked. Only about half of the time. I am using async, is that part of the issue. Here's my code snippet:

Consumer creation:

```javascript
    const sqs = Consumer.create({
      queueUrl: this.configService.get('SQS_QUEUE_URL'),
      handleMessage: (message, done) => this.handleSQSMessage(message, done),
    });
    sqs.on('error', (error) => this.handleSQSError(error));
    sqs.start();
```

Callback:
```javascript
  async handleSQSMessage(message, done) {
    console.log('message: ', message);
    await this.someOtherAsyncMethodToUpdateMyDatabase(message);
    done();
  }
```

The console log message only fires about half of the time, but 100% of messages are being deleted from the queue somehow.

**Comment by kodayashi** [comment]
I've simplified the setup, but it's still not being called reliably. Messages are getting deleted from the queue however.

```javascript
    const sqs = Consumer.create({
      queueUrl: this.configService.get('SQS_QUEUE_URL'),
      handleMessage: (message, done) => { console.log(message); done(); },
    });
    sqs.on('error', (error) => this.handleSQSError(error));
    sqs.start();
```

**Comment by kodayashi** [comment]
Just following up here, I'm seeing intermittent issues where this library removes messages from the queue, but handleMessage is never fired.

**Comment by cejast** [comment]
Hi @kodayashi 

I'm curious about the problems you're experiencing in your examples, since messages will only get removed when `done` is invoked in `handleMessage` without an error - so if messages are indeed being deleted, then it's being called as expected.

It might be the case that an error is not being handled somewhere in between. You should handle any errors encountered during `handleMessage` and pass it through the callback, e.g. `done(err)`. This will emit an error and won't delete the message from the queue - see [here](https://github.com/bbc/sqs-consumer#usage) for more info.

**Comment by kodayashi** [comment]
You should be curious, it doesn't make any sense @cejast.

After a bit of luck I realized there was a rogue service that was also polling SQS, so there was a race condition where the other service was popping items from the queue. The library is working just fine :)

Passing in an async handler also works fine. Sorry for the false alarm. I suppose on the plus side, I learned quite a bit about async, auto-bind and EventEmitter from this library. Oops!
