### ISSUE TITLE
Interested in the design decision for handler and emitter

### ISSUE THREAD

**Issue by tbenade** [bbc/sqs-consumer#13]
Hi,

Curious as to why the handleMessage function is mandatory when you have an event emitter for message_received implemented?

If handleMessage is mandatory does it not deem the event emitter redundant as you have to implement both. Any insights much appreciated as it is a great looking bit of code to learn from.

Thanks

**Comment by robinjmurphy** [comment]
Hi @tbenade. We only use the event for logging and incrementing metrics.

I can see it's a little confusing, but the main reason for making the `handleMessage` a mandatory option is that we _dont'_ want the possibility of multiple listeners trying to delete the same message, which is why the event only provides you with the message - it doesn't try to delete it.

**Comment by tbenade** [comment]
crystal! thanks
