### ISSUE TITLE
AWS client timeouts

### ISSUE THREAD

**Issue by nspragg** [bbc/sqs-consumer#137]
We need to investigate the potential for SQS clients calls hanging (for example, due to underlying network issues). This is related to #136 and #130 

**This was originally raised by @ShahidH. Original issue description:**
It looks like return `await this.sqs.receiveMessage(params).promise();` hanged forever which has caused consumer suddenly stops polling for new messages.

I suspect AWS has added throttle limit for `receiveMessage()` when executing outside of AWS network. But running directly from AWS Lambda on their network then there is no issue.

**Comment by ht2** [comment]
To note - we are also seeing timeouts _within_ an AWS VPC: 

```
1|Worker  | { message: 'SQS receive message failed: Connection timed out after 120000ms',
1|Worker  |   stack: 'SQSError: SQS receive message failed: Connection timed out after 120000ms\n    at Consumer._handleSqsResponse (/usr/local/learninglocker/releases/ll-20181105-e2e83cfa00ea556275ea020bb04a60925311d627/webapp/node_modules/sqs-consumer/index.js:124:24)
```

**Comment by tuan-pham** [comment]
I think the problem is because the connection is held for too long when sqs-consumer does long polling. Lambda has no problem because of its execution time (maximum 15 mins).

We have the same problem when running long polling using sqs-consumer. The difference here is that we have a proxy in the middle, and the workaround is to config AWS.config to to timeout the connection every 2 mins.
`     AWS.config.update({
         httpOptions: { agent: proxy({ host, port, timeout }) }
     })
`
