### ISSUE TITLE
"messaged_received" event no longer emitted when consumer was previously started

### ISSUE THREAD

**Issue by randyxli** [bbc/sqs-consumer#195]
### Description

If a consumer is created, started, and stopped, and then another consumer is created and started, then that second consumer no longer emits the `message_received` event.

### Expected behaviour

The second consumer should emit the `message_received` event upon receiving a message.

### Actual behaviour

The second consumer receives the message but does not emit the `message_received` event.

### Steps to reproduce

I set up a small repo to demonstrate the bug. Requirements are Node 8+ and docker-compose.

```bash
git clone git@github.com:TakeScoop/sqs-test.git
git reset 1d5a965369ea83c14c1350262fdd8ce295801705 # specify commit for posterity
cd sqs-test
nvm use # if you use nvm
npm install
docker-compose -f test/docker-compose.yml up -d
DEBUG=sqs-consumer npm run test
```

The second test, `should get message_received event`, fails. The debug output clearly shows that the message was received. If you run it by itself using `.only`, then it passes. Similarly, if you comment out the `consumer.start()` on the preceding line, then it also passes.

### Operating system

I'm running macOS 10.14.6

**Comment by numman** [comment]
Heys Guys, 

I had this issue recently too and it turns out this only seems to happen when you send the message using the same SQS client that you use in Consumer.create({});

I created two separate SQS clients, one for the consumer and one to send messages with and it works without any issues. 

Try it out and let me know how it goes!
