### ISSUE TITLE
Concurrency limits based on CPU cores/processing power

### ISSUE THREAD

**Issue by kceb** [bbc/sqs-consumer#201]
I'm used to using libraries like sidekiq for ruby where concurrency was determined by CPU cores/processing power, where you'd have around one worker per core and then each worker could process around 25 threads. This gives a machine the ability to process around 50 jobs concurrently. What are the concurrency recommendations for using this library? I've seen other posts where people set up multiple consumers. Is there a guideline on how many consumers we can set up?

Is it more of a guess and check?

**Comment by BrutalSimplicity** [comment]
Node runs on a single-thread so by default, you cannot have multiple threads or processes. However, you can achieve this using the `cluster` module or something like pm2 in cluster mode. 

You should also be able to increase concurrency/throughput by increasing the number of async requests to the SQS API. However, the library does not appear to support this type of concurrency as it only polls for messages after they are handled. It seems like this could be a feature request, but I'm curious what the creator/maintainer thinks about it. If this is a feature that makes sense, I wouldn't mind adding support for it, as the change _seems_ to be fairly straightforward.

**Comment by crh3675** [comment]
We achieve a multi-threaded service by allowing the main process to spawn multiple child processes.  When using spawn, the server will use all available threads.  We needed to do this because our throughput was so high and we kept getting a deep backlog of messages. We setup about 8 SQS listeners to the same channel that pipe into Redis pub/sub which the main process reads from.
