### ISSUE TITLE
Message Attributes not working

### ISSUE THREAD

**Issue by bhavesh-pandey** [bbc/sqs-consumer#243]
**Question**
Hi I am using sqs-consumer to listen to my SQS queue subscribed to a SNS topic. Its listening to all the messages. No issues there. I have put some filters in SNS subscription (screenshot 1). Also configured it in my code (screenshot 2). I tried all permutation combinations of setting it only to attributeNames field, setting it only to messageAttributeNames filed, setting it to both, but nothing is working, I am receiving all messages, no matter which filter it has (screenshot 3)

** **

**Screenshots**
<img width="238" alt="Screenshot 2020-11-09 at 1 42 25 AM" src="https://user-images.githubusercontent.com/23245538/98483270-d4db9d80-222c-11eb-82d5-4e92fe444ab1.png">
SNS filters (1)
  
  ** **
<img width="472" alt="Screenshot 2020-11-09 at 1 43 44 AM" src="https://user-images.githubusercontent.com/23245538/98483295-03f20f00-222d-11eb-9652-69c49bd825f1.png">
Message attributes in code (2)
  
  ** **
<img width="516" alt="Screenshot 2020-11-09 at 1 46 13 AM" src="https://user-images.githubusercontent.com/23245538/98483337-5d5a3e00-222d-11eb-8a88-39b72e6194a0.png">
Received message which has other filters too (3)

** **

Am I doing anything wrong here?

**Comment by joaovrgumiero** [comment]
I have the same question, is it possible to have a consumer for each specific attribute?

**Comment by recoiladam** [comment]
From what I can tell, this is not possible. I think what you might need to do is some how determine if it's a message that you want to process and if not, "fail" the message so that it gets returned to the queue. It would be nice if we had some kind of pre-processing event that you could simply return true (process message) or false (do not process message and put message back into queue).
