### ISSUE TITLE
`handleMessage` type check on thrown errors

### ISSUE THREAD

**Issue by auzwang** [bbc/sqs-consumer#288]
**Describe the bug**
According to usage docs:
> Throwing an error (or returning a rejected promise) from the handler function will cause the message to be left on the queue. An SQS redrive policy can be used to move messages that cannot be processed to a dead letter queue.

It appears that the `handleMessage` and `handleMessageBatch` [type definitions](https://github.com/bbc/sqs-consumer/blob/master/src/consumer.ts#L91) specify `Promise<void>` instead of `Promise<void | Error>`.

Supplying a `handleMessage` function that throws errors results in:
> TS2345: Argument of type '(message: Message) => Promise<Error>' is not assignable to parameter of type '(message: Message) => Promise<void>'.   Type 'Promise<Error>' is not assignable to type 'Promise<void>'.     Type 'Error' is not assignable to type 'void'.

**To Reproduce**
Steps to reproduce the behaviour:
1. Define a `handleMessage` function with throws an error.
2. Pass said function into `Consumer.create({ ..., handleMessage })`

**Expected behaviour**
Passing a `handleMessage` function that throws errors should not result in type check errors.

**Comment by SishaarRao** [comment]
@auzwang Even if a function throws an error, the return type would still be `Promise<void>`. Thrown values are not reflected in function's return type, as thrown values are handled differently than return values.

This is also why when you do a try / catch, the type of the caught value is technically `any` or `unknown`, since any type of value (not just an Error) can be thrown. 

In order to convey information about possible thrown errors, I would suggest using JSDoc's with the `@throws` annotation
