### ISSUE TITLE
Stop consuming queue messages

### ISSUE THREAD

**Issue by thierryskoda** [bbc/sqs-consumer#69]
Hi, 

I'm doing some test locally with my queue. I'm sending 100 messages in a loop in my queue and using `sqs-consumer` to consume those messages but it always stop around 50-60 messages consumed. I'm using a batch size of 5 and everything works perfectly for the first 50-60 messages but he rest of the messages stay in `Message in flight` in AWS SQS and I'm not able to process them. 

Thank you very much for any help!

Here is my code

```
const queueSendMessage = Consumer.create({
        messageAttributeNames: ["All"],
        batchSize: 5,
        queueUrl: process.env.AWS_SQS_QUEUE_URL,
        handleMessage: (message, done) => {
            done()
        },
        sqs: new AWS.SQS({
            accessKeyId: process.env.AWS_ACCESS_KEY_ID,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
            region: 'us-east-1'
        })
    });
     
    queueSendMessage.on('error', (err) => {
        console.log("ERROR SQS:", err.message);
    });

queueSendMessage.start();
```

**Comment by niklasR** [comment]
Hello,
The `Message in flight` status usually means that the message has been received, and is being processed.
It'll remain `in flight` until it is either deleted off the queue once it's been processed or until the `Default Visibility Timeout` is reached. In the latter case it'll be put back onto the queue unless a `Redrive Policy` specifies something different.

Have you tried checking the contents of the message to see if it is the first 50,-60 or just a random 50 of the 100?


Also, have you tried logging out other [events](https://github.com/bbc/sqs-consumer#events) from the queueSendMessage? Especially `message_received` and `message_processed`. 

Since the messages are `in flight`, they should've been `received`, but not `processed` - it would be great if you could confirm that. Have a look at the snippet below to see how you can log out all events emitted by the consumer.

```js
const Consumer = require('sqs-consumer');

function logAllEmitterEvents(eventEmitter) {
  const emitToLog = eventEmitter.emit;

  eventEmitter.emit = function () {
    const event = arguments[0];
    console.log("event emitted: " + event);
    emitToLog.apply(eventEmitter, arguments);
  }
}

const app = Consumer.create({
  messageAttributeNames: ["All"],
  batchSize: 5,
  queueUrl: process.env.AWS_SQS_QUEUE_URL,
  handleMessage: (message, done) => {
    console.log('Handling message..', message.MessageId, message.Body);
    done();
  }
});

logAllEmitterEvents(app);

app.start();
```

**Comment by thierryskoda** [comment]
Yes I checked `message_received` and `message_processed`. I think my main error was that I tough AWS SQS was good for real time but it since it's not?

**Comment by nspragg** [comment]
@thierryskoda - the AWS SQS docs should help you decide if SQS is suitable for the problem you're trying to solve:
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/Welcome.html

Closing issue as this library is behaving as expected. Thanks.

**Comment by MohitVachhani** [comment]
> Yes I checked `message_received` and `message_processed`.
> 
> Can it be because AWS SQS is not good for real time message processing?

Use kinesis for real time message processing!
